steps:

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'rssfeedreader', '--project=rssfeedreader', '--region=us-west1', '--allow-unauthenticated', '--source=.']

- name: 'ubuntu'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        apt update
        apt install -y curl sudo
        curl -sL https://firebase.tools | bash
        mkdir public
        touch public/placeholder.html
        ls -lah
        firebase deploy --project=rssfeedreader
