steps:

- name: 'golang'
  args: ['go', 'build']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['app', 'deploy', '--project=rssfeedreader', '--version=$SHORT_SHA']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'rssfeedreader', '--project=rssfeedreader', '--region=us-west1', '--source=.']

- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy', '--project=rssfeedreader']
